apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-cert-pv-cas-gateway-service
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.125.176
    path: "/data/tanzu-cert-springboot-password-decryption"