apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-cas-gateway-service
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.125.176
    path: "/data/tanzu-ns-test-dc02-common-apps/cas-lead"