apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-cas-gateway-service
  namespace: cas
  labels:
    app.kubernetes.io/name: cas-gateway-service
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv-cas-gateway-service