apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-cert-pvc-cas-gateway-service
  namespace: cas
  labels:
    app.kubernetes.io/name: cas-gateway-service
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
  volumeName: shared-cert-pv-cas-gateway-service